services:
  site:
    image: lucastsuzukusptech/intelvision_site:1.81
    ports:
      - "8080:8080"
      - "3333:3333"
    networks:
      - rede-compose
    depends_on:
      - database
  database:
    image: lucastsuzukusptech/intelvision_database:1.5
    ports:
      - "3306:3306"
    networks:
      - rede-compose
  s3viewer:
    image: lucastsuzukusptech/intelvision_s3viewer_lucas:1.8
    ports:
      - "3000:3000"
    networks:
      - rede-compose
networks:
  rede-compose:
    driver: bridge
